Update requirements.txt
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

The `getsize` function was removed in Pillow 10, downgrading to Pillow 9.5.0 fixed the issue above.