Fix webhook spam
Logs:
`[2022-05-21 19:25:10][ERROR][bot]: Event 'on_message' caused an exception
Traceback (most recent call last):
  File "/home/teeworlds/pybot/ddnet-discordbot/.venv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/teeworlds/pybot/ddnet-discordbot/cogs/moderator.py", line 198, in on_message
    or is_staff(author) or f'<@&{ROLE_MODERATOR}>' not in message.content or message.author.bot:
  File "/home/teeworlds/pybot/ddnet-discordbot/cogs/moderator.py", line 29, in is_staff
    return any(r.id in (ROLE_ADMIN, ROLE_MODERATOR) for r in member.roles)
AttributeError: 'User' object has no attribute 'roles'`
Happens everytime someone sends a message via webhook in #developer